Environment=QA
Base.URL=https://demoblaze.com/
Browser=chromium
OS=darwin 25.4.0
Node.Version=v22.11.0
OS.Architecture=arm64
Hostname=Ranjeet-MacBook-Pro.local
User=ranjeetkendre
Timestamp=2026-05-12T17:48:04.208Z
Framework=Playwright + JavaScript + POM
Parallel.Workers=3
Retries=1
Headless=true